# Generated by Django 4.0.6 on 2022-08-01 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('email', models.CharField(default='', max_length=50, unique=True, verbose_name='Email')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ACFTResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gender', models.CharField(default='F', max_length=6)),
                ('age', models.IntegerField(default=0, max_length=2)),
                ('deadlift_raw', models.IntegerField(default=0)),
                ('deadlift_score', models.IntegerField(default=0)),
                ('pushups_raw', models.IntegerField(default=0)),
                ('pushups_score', models.IntegerField(default=0)),
                ('spt_raw', models.FloatField(default=0, max_length=3)),
                ('spt_score', models.IntegerField(default=0)),
                ('sdc_raw', models.IntegerField(default=0)),
                ('sdc_score', models.IntegerField(default=0)),
                ('plank_raw', models.IntegerField(default=0)),
                ('plank_score', models.IntegerField(default=0)),
                ('tmr_raw', models.IntegerField(default=0)),
                ('tmr_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acft_results', to='api.user')),
            ],
        ),
    ]
