# Generated by Django 4.0.6 on 2022-08-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acftresult',
            name='date',
        ),
        migrations.AddField(
            model_name='acftresult',
            name='day',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='acftresult',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='acftresult',
            name='year',
            field=models.IntegerField(blank=True, default=2022),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='deadlift_raw',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='deadlift_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='gender',
            field=models.CharField(blank=True, default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='plank_raw',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='plank_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='pushups_raw',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='pushups_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='sdc_raw',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='sdc_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='spt_raw',
            field=models.FloatField(blank=True, default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='spt_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='tmr_raw',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='tmr_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='total_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
