# Generated by Django 4.0.6 on 2022-08-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_acftresult_date_acftresult_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acftresult',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='month',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
