# Generated by Django 4.0.6 on 2022-08-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_acftresult_age_alter_acftresult_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acftresult',
            name='spt_raw',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
