# Generated by Django 4.0.6 on 2022-08-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_acftresult_spt_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='acft_results', to='api.user'),
        ),
    ]
