# Generated by Django 4.0.6 on 2022-08-14 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_paid_fee_alter_acftresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paid_fee',
        ),
        migrations.AlterField(
            model_name='acftresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acft_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
