# Generated by Django 4.0.6 on 2022-08-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_acftresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_fee',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
