# Generated by Django 4.0.6 on 2022-08-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_paid_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent', models.IntegerField(blank=True, default=1)),
                ('ephemeral_key', models.IntegerField(blank=True, default=1)),
                ('customer', models.IntegerField(blank=True, default=2022)),
                ('publishable_key', models.IntegerField(blank=True, default=2022)),
            ],
        ),
    ]
