# Generated by Django 4.0.6 on 2022-08-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_paymentsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsheet',
            name='customer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentsheet',
            name='ephemeral_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentsheet',
            name='payment_intent',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentsheet',
            name='publishable_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
